# Generated by Django 5.2 on 2025-05-03 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Equipment name')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Inventory number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Equipment image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Commissioning date')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('out_of_order', 'Out of Order'), ('decommissioned', 'Decommissioned')], default='operational', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='api.site', verbose_name='Site')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='api.workshop', verbose_name='Workshop')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='api.equipmenttype', verbose_name='Equipment type')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ('inventory_number',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Document name')),
                ('document', models.FileField(upload_to='equipment_documents/', validators=[django.core.validators.FileExtensionValidator(('pdf',))], verbose_name='Document file')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.equipment', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Equipment Document',
                'verbose_name_plural': 'Equipment Documents',
                'ordering': ('-upload_date',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Specification name')),
                ('specifications_description', models.TextField(blank=True, verbose_name='Specification description')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='api.equipmenttype')),
            ],
            options={
                'verbose_name': 'Equipment Specification',
                'verbose_name_plural': 'Equipment Specifications',
                'ordering': ('equipment_type', 'name'),
                'unique_together': {('equipment_type', 'name')},
            },
        ),
    ]
